### PR TITLE
docs: added the architecture diagram

### PR DESCRIPTION
**Pull request by JuliusKryger**

### CODE REVIEW

**Review by idax6797 — APPROVED** [review]
Looks good to me 👍🏼

**Review by MarLaslo — CHANGES_REQUESTED** [review]
What if we rename groups to Service Layer, Business Layer and Data Access layer.

And then what we have in squares:
Data Access Layer (DbContext) just to Database Context

Service Layer to Repositories or Services.

Business Layer to Business Logic

Web Service Layer to Web Service or Web API?

**Review by JuliusKryger — COMMENTED** [review]
Looks Good now!

**Review by MarLaslo — APPROVED** [review]
All good

**Pull request merged**
