### PR TITLE
feat: link references

### PR DESCRIPTION
**Pull request by idax6797**
> [!IMPORTANT]  
> Where not able to implement on /users/id/bookmarks and /users/id/completed, ping @JuliusKryger 
> Paging on similar_media not working properly

This pull request includes several updates to various controllers in the `CitMovie.Api` project, focusing on enhancing functionality and adding new features. The most important changes include adding new dependencies to controllers, updating methods to include pagination and links, and refactoring existing methods for better clarity and functionality.

### Enhancements to Controllers:
* **BookmarkController**:
  * Added dependencies: `IUserManager`, `IMediaManager`, and `PagingHelper`.
  * Updated `GetBookmark` and `GetUserBookmarks` methods to include links and pagination.
  * Added `AddBookmarkLinks` method to generate links for bookmarks.

* **CompletedController**:
  * Added dependencies: `IUserManager`, `IMediaManager`, and `PagingHelper`.
  * Updated `GetCompleted` and `GetUserCompleted` methods to include links and pagination.
  * Added `AddCompletedLinks` method to generate links for completed items.

* **FollowController**:
  * Added dependency: `IPersonManager`.
  * Updated `GetFollowings` method to include links.
  * Added `AddFollowingLinks` method to generate links for followings.

* **MediaController**:
  * Added dependency: `PagingHelper`.
  * Updated `Get`, `GetSimilar`, and `GetRelated` methods to include links and pagination. [[1]](diffhunk://#diff-fb81e49fc5413a36636bdf4e2c9db9a4463bef4cb0210fca00eb09ead5cfd472R11-R185) [[2]](diffhunk://#diff-fb81e49fc5413a36636bdf4e2c9db9a4463bef4cb0210fca00eb09ead5cfd472R1-R2)
  * Added `AddMediaBasicLinks` and `AddMediaLinks` methods to generate links for media items.

* **PersonController**:
  * Added dependency: `IMediaManager`.
  * Updated `GetPersonById` method to include media links.

### CODE REVIEW

**Comment by MarLaslo** [comment]
Have tested the promotional media, looking cool :)

**Review by MarLaslo — APPROVED** [review]
tested promotional media looking cool :)

**Review by sofushn — CHANGES_REQUESTED** [review]
Instead of adding `Links` property to all dtos, we should have a base class `BaseResult` that contains the links property

**Review by sofushn — APPROVED** [review]
Fixed it myself

**Pull request merged**
